### ISSUE TITLE
exposing Lazy

### ISSUE THREAD

**Issue by ggPeti** [turboMaCk/lazy-tree-with-zipper#49]
Hey @turboMaCk!

I would like to be able to use Lazy.map in order to lift regular list functions (such as `take`) into LList. Would you mind exposing the Lazy module to users?

My immediate use case is to implement a `trunk` tree function that prunes all but the first children. I can do that like

```
trunk : Tree a -> Tree a
trunk (Tree a branches) =
    case LList.head branches of
        Just tree ->
            Tree a <| LList.singleton <| trunk tree

        Nothing ->
            Tree a LList.empty
````

But with `Lazy.map` I would be able to

```
trunk : Tree a -> Tree a
trunk (Tree a branches) =
    Tree a <| Lazy.map (List.map trunk << List.take 1) branches
```
which would not only be terser, but actually keep laziness too.

If exposing the entirety of Lazy seems like an overkill, an alternative I see is exposing a function like `LList.liftLazy` or some such, which would be just Lazy.map for LLists.

Also, I saw lazy fold functions in LList, but they are not exposed. They would solve my problem, but exposing a more general interface would obviate the need for exposing such lazy-lifted list functions one by one.

**Comment by turboMaCk** [comment]
I think we can expose Lazy module. It seems elm/lazy won't be making come back. It will require some updates in documentation of the module since it uses some syntax that is no longer valid in elm. Do you want to open the PR for this?

**Comment by ggPeti** [comment]
I can come around to do it in the following days!
